Feature/about
yohdev/gatsby-wp pull request #12
Opened 2022-06-22 18:45 UTC by yohdev-travis

2022-07-15 19:27 UTC, yohdev-von requested changes
@yohdev-travis 
This was pushed prior to the last review. Some of the same things I requested change for occurred in this.

2022-07-15 19:27 UTC, yohdev-von commented on package.json
> +    "react-responsive-carousel": "^3.2.23",
@ayohdev 
Is this the correct carousel we are using?

2022-07-15 19:27 UTC, yohdev-von commented on src/components/Hero.js
> +const Hero = (props) => {
Destructure props like the last review.
(props) should be ({heading, subtitle, etc})

2022-07-15 19:27 UTC, yohdev-von commented on src/components/reusuables/YohDevButton.js
> +const YohDevButton = (props) => {
Destructure props like the last review.
(props) should be ({heading, subtitle, etc})

2022-07-15 19:27 UTC, yohdev-von commented on src/components/reusuables/cards/CardVerticalHover.js
> +const CardVerticalHover = (props) => {
Destructure props like the last review.
(props) should be ({heading, subtitle, etc})

2022-07-15 19:27 UTC, yohdev-von commented on src/components/reusuables/cards/TeamCard.js
> +const TeamCard = (props) => {
Destructure props like the last review.
(props) should be ({heading, subtitle, etc})

2022-07-15 19:27 UTC, yohdev-von commented on src/components/reusuables/cards/Testimonialcard.js
> +const Testimonialcard = (props) => {
Destructure props like the last review.
(props) should be ({heading, subtitle, etc})

2022-07-15 19:27 UTC, yohdev-von commented on src/components/reusuables/content/ClientLogosInline.js
> +const ClientLogosInline = (props) => {
Destructure props like the last review.
(props) should be ({heading, subtitle, etc})

2022-07-15 19:27 UTC, yohdev-von commented on src/components/reusuables/content/ImageWithText.js
> +const ContentAll = (props) => {
Destructure props like the last review.
(props) should be ({heading, subtitle, etc})

2022-07-15 19:27 UTC, yohdev-von commented on src/components/reusuables/content/ImageWithText.js
> +          {props.contentHeading == "true" ? (
This should be something like contentHeading && { }. "true" prop should be replaced with Boolean true.

2022-07-15 19:27 UTC, yohdev-von commented on src/components/reusuables/content/ImageWithText.js
> +            ""
Remove the empty string in the else. We do not need the else. : ( 
""
)

2022-07-15 19:27 UTC, yohdev-von commented on src/components/reusuables/content/ImageWithText.js
> +          ) : (
Remove the empty string in the else. We do not need the else. : ( 
""
)

2022-07-15 19:27 UTC, yohdev-von commented on src/components/reusuables/content/ImageWithText.js
> +          {props.contentButton == "true" ? (
This should be something like contentHeading && { }. "true" prop should be replaced with Boolean true.

2022-07-15 19:27 UTC, yohdev-von commented on src/components/reusuables/sections/TeamSection.js
> +const TeamSection = (props) => {
Destructure props like the last review.
(props) should be ({heading, subtitle, etc})

2022-07-15 19:27 UTC, yohdev-von commented on src/components/reusuables/sections/TeamSection.js
> +  const TeamData = [
Lower case to teamData.

2022-07-15 19:27 UTC, yohdev-von commented on src/components/reusuables/sections/TestimonialSection.js
> +const TestimonialSection = (props) => {
Destructure props like the last review.
(props) should be ({heading, subtitle, etc})

I'm not sure I see any props being used in this one. Can be empty for now.

2022-07-15 19:27 UTC, yohdev-von commented on src/components/reusuables/sections/YohdevSection.js
> +const YohdevSection = (props) => {
Destructure props like the last review.
(props) should be ({heading, subtitle, etc})

2022-07-15 19:27 UTC, yohdev-von commented on src/components/reusuables/sections/YohdevSection.js
> +    props.sectionContainerStyle == "default"
This will be updated after destructuring to just sectionContainerStyle.

2022-07-15 19:27 UTC, yohdev-von commented on src/components/reusuables/sections/YohdevSection.js
> +        {props.button == "true" ? (
This should be something like button && { }. "true" prop should be replaced with Boolean true.

2022-07-15 19:27 UTC, yohdev-von commented on src/components/reusuables/sections/YohdevSection.js
> +        {props.children}
Desctructuring may effect this props.children. Reach out to me if that breaks this and you can't get it to work.

2022-07-28 23:52 UTC, ayohdev approved these changes

2022-07-28 23:55 UTC, ayohdev approved these changes

2022-07-28 23:55 UTC, merged